version: "3"
services:
  postgres:
    image: postgres:9.5
    network_mode: bridge
    container_name: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=docker
    restart: unless-stopped